<?php

class DVMD_Table_Maker extends DiviExtension {

    /**
     * The gettext domain for the extension's translations.
     *
     * @since 2.0.2
     *
     * @var string
     */
    public $gettext_domain = 'dvmd-table-maker';

    /**
     * The extension's WP Plugin name.
     *
     * @since 2.0.0
     *
     * @var string
     */
    public $name = 'divi-modules-table-maker';

    /**
     * The extension's version
     *
     * @since 2.0.2
     *
     * @var string
     */
    public $version = '2.0.2';

    /**
     * DVMD_Table_Maker constructor.
     *
     * @since 2.0.1
     *
     * @param string $name
     * @param array  $args
     */
    public function __construct( $name = 'divi-modules-table-maker', $args = array() ) {
        $this->plugin_dir = plugin_dir_path( __FILE__ );
        $this->plugin_dir_url = plugin_dir_url( $this->plugin_dir );
        add_filter('the_content', array($this, 'dvmd_tm_escape_newline'), 9);
        add_filter('the_content', array($this, 'dvmd_tm_unescape_newline'));
        parent::__construct( $name, $args );
    }


    /**
     * Escape newline from content by converting \n into {{dvmd_newline}}.
     * Default wpautop priority is 10, we use 9 to execute this before wpautop.
     *
     * @since   2.0.1
     * @access  public
     *
     * @param   string  $content
     * @return  string
     * @action  the_content
     */
    public function dvmd_tm_escape_newline($content) {
        if ($this->dvmd_tm_should_escape_newline()) {
            return preg_replace_callback(
                "/\[dvmd_table_maker_item[^]]*]/",
                array($this, 'dvmd_tm_newline_to_placeholder'),
                $content
            );
        }
        return $content;
    }


    /**
     * Restore newline to content by converting {{dvmd_newline}} into \n.
     * Default wpautop priority is 10, we use 10 to execute this soon after wpautop.
     *
     * @since   2.0.1
     * @access  public
     *
     * @param   string  $content
     * @return  string
     * @action  the_content
     */
    public function dvmd_tm_unescape_newline($content) {
        if ($this->dvmd_tm_should_escape_newline()) {
            return preg_replace_callback(
                "/\[dvmd_table_maker_item[^]]*]/",
                array($this, 'dvmd_tm_placeholder_to_newline'),
                $content
            );
            return $content;
        }
        return $content;
    }


    /**
     * Checks whether is single post, is on frontend (ie. not Visual Builder)…
     * and the post content is generated by Divi Builder.
     *
     * @since   2.0.1
     * @access  private
     *
     * @return  boolean
     */
    private function dvmd_tm_should_escape_newline() {
        return
            is_singular() &&
            !et_core_is_fb_enabled() &&
            'on' === get_post_meta(get_the_ID(), '_et_pb_use_builder', true);
    }


    /**
     * Callback function to convert \n into {{dvmd_newline}}.
     *
     * @since   2.0.1
     * @access  public
     *
     * @param   array  $matches
     * @return  string
     */
    public function dvmd_tm_newline_to_placeholder($matches) {
        $old_match = et_()->array_get($matches, '0', '');
        $new_match = preg_replace("/\n/", "{{dvmd_newline}}", $old_match);
        return $new_match;
    }


    /**
     * Callback function to convert {{dvmd_newline}} into \n.
     * Firstly, removes additional newlines created by wpautop for…
     * nested html elements (eg. <cell><h1>Hello World</h1><cell>).
     *
     * @since   2.0.1
     * @access  public
     *
     * @param   array  $matches
     * @return  string
     */
    public function dvmd_tm_placeholder_to_newline($matches) {
        $old_match = et_()->array_get($matches, '0', '');
        $new_match = preg_replace("/\n<p>|<\/p>\n|\n/", "", $old_match);
        $new_match = preg_replace("/{{dvmd_newline}}/", "\n", $new_match);
        return $new_match;
    }
}

new DVMD_Table_Maker;
